input {
  file {
    path => "/data/results.jsonl"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  mutate {
    rename => { "timestamp_utc" => "@timestamp" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elk_elasticsearch:9200"]
    index => "harmbench-results"
  }
  stdout { codec => dots }
}