input {
  file {
    path => "/data/scores.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    skip_header => true
    columns => ["run_id","prompt_id","type","category","model","expected_behavior","predicted_behavior","is_correct","error"]
  }

  mutate {
    convert => { "is_correct" => "integer" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elk_elasticsearch:9200"]
    index => "harmbench-scores"
  }
  stdout { codec => dots }
}